### ISSUE TITLE
upgrade to ES 8.16

### ISSUE THREAD

**Issue by ymarcon** [obiba/mica-search-es8#1]
Currently it does not compile with `8.16.1`:

```
[ERROR] /home/yannick/projects/mica-search-es8/src/main/java/org/obiba/es/mica/ESSearcher.java:[127,54] cannot find symbol
[ERROR]   symbol:   method of((g)->g)
[ERROR]   location: class co.elastic.clients.elasticsearch._types.aggregations.GlobalAggregation
[ERROR] /home/yannick/projects/mica-search-es8/src/main/java/org/obiba/es/mica/ESSearcher.java:[208,56] cannot find symbol
[ERROR]   symbol:   method of((g)->g)
[ERROR]   location: class co.elastic.clients.elasticsearch._types.aggregations.GlobalAggregation
[ERROR] /home/yannick/projects/mica-search-es8/src/main/java/org/obiba/es/mica/ESSearcher.java:[262,56] cannot find symbol
[ERROR]   symbol:   method of((g)->g)
[ERROR]   location: class co.elastic.clients.elasticsearch._types.aggregations.GlobalAggregation
[ERROR] /home/yannick/projects/mica-search-es8/src/main/java/org/obiba/es/mica/ESSearcher.java:[312,56] cannot find symbol
[ERROR]   symbol:   method of((g)->g)
[ERROR]   location: class co.elastic.clients.elasticsearch._types.aggregations.GlobalAggregation
[ERROR] /home/yannick/projects/mica-search-es8/src/main/java/org/obiba/es/mica/support/AggregationParser.java:[123,86] incompatible types: java.lang.String cannot be converted to java.lang.Double
[ERROR] /home/yannick/projects/mica-search-es8/src/main/java/org/obiba/es/mica/support/AggregationParser.java:[125,88] incompatible types: java.lang.String cannot be converted to java.lang.Double
[ERROR] /home/yannick/projects/mica-search-es8/src/main/java/org/obiba/es/mica/support/AggregationParser.java:[127,88] incompatible types: java.lang.String cannot be converted to java.lang.Double
[ERROR] /home/yannick/projects/mica-search-es8/src/main/java/org/obiba/es/mica/query/RQLQuery.java:[447,62] cannot find symbol
[ERROR]   symbol:   method field(java.lang.String)
[ERROR]   location: class co.elastic.clients.elasticsearch._types.query_dsl.RangeQuery.Builder
[ERROR] /home/yannick/projects/mica-search-es8/src/main/java/org/obiba/es/mica/query/RQLQuery.java:[457,20] cannot find symbol
[ERROR]   symbol:   method lt(co.elastic.clients.json.JsonData)
[ERROR]   location: variable builder of type co.elastic.clients.elasticsearch._types.query_dsl.RangeQuery.Builder
[ERROR] /home/yannick/projects/mica-search-es8/src/main/java/org/obiba/es/mica/query/RQLQuery.java:[459,20] cannot find symbol
[ERROR]   symbol:   method gte(co.elastic.clients.json.JsonData)
[ERROR]   location: variable builder of type co.elastic.clients.elasticsearch._types.query_dsl.RangeQuery.Builder
[ERROR] /home/yannick/projects/mica-search-es8/src/main/java/org/obiba/es/mica/query/RQLQuery.java:[461,20] cannot find symbol
[ERROR]   symbol:   method gte(co.elastic.clients.json.JsonData)
[ERROR]   location: variable builder of type co.elastic.clients.elasticsearch._types.query_dsl.RangeQuery.Builder
[ERROR] /home/yannick/projects/mica-search-es8/src/main/java/org/obiba/es/mica/query/RQLQuery.java:[462,20] cannot find symbol
[ERROR]   symbol:   method lt(co.elastic.clients.json.JsonData)
[ERROR]   location: variable builder of type co.elastic.clients.elasticsearch._types.query_dsl.RangeQuery.Builder
[ERROR] /home/yannick/projects/mica-search-es8/src/main/java/org/obiba/es/mica/query/RQLQuery.java:[512,34] cannot find symbol
[ERROR]   symbol:   method field(java.lang.String)
[ERROR]   location: variable q of type co.elastic.clients.elasticsearch._types.query_dsl.RangeQuery.Builder
[ERROR] /home/yannick/projects/mica-search-es8/src/main/java/org/obiba/es/mica/query/RQLQuery.java:[520,34] cannot find symbol
[ERROR]   symbol:   method field(java.lang.String)
[ERROR]   location: variable q of type co.elastic.clients.elasticsearch._types.query_dsl.RangeQuery.Builder
[ERROR] /home/yannick/projects/mica-search-es8/src/main/java/org/obiba/es/mica/query/RQLQuery.java:[528,34] cannot find symbol
[ERROR]   symbol:   method field(java.lang.String)
[ERROR]   location: variable q of type co.elastic.clients.elasticsearch._types.query_dsl.RangeQuery.Builder
[ERROR] /home/yannick/projects/mica-search-es8/src/main/java/org/obiba/es/mica/query/RQLQuery.java:[536,34] cannot find symbol
[ERROR]   symbol:   method field(java.lang.String)
[ERROR]   location: variable q of type co.elastic.clients.elasticsearch._types.query_dsl.RangeQuery.Builder
[ERROR] /home/yannick/projects/mica-search-es8/src/main/java/org/obiba/es/mica/query/RQLQuery.java:[544,34] cannot find symbol
[ERROR]   symbol:   method field(java.lang.String)
[ERROR]   location: variable q of type co.elastic.clients.elasticsearch._types.query_dsl.RangeQuery.Builder
```

**Comment by kazoompa** [comment]
The Mica is currently compatible with the ES8 version I had left in the docker-mica.

I had started upgrading the plugin but never got to finish it. I will take a look, some APIs have changed again.

**Comment by kazoompa** [comment]
Created a new branch but still have errors ...
